theme: minima
title: High-Fidelity CFD Verification Workshop
author: Organizing committee
email: hfcfdw@gmail.com
description: >
  An aerospace community effort towards verification of high-fidelity CFD methodologies.
header_pages:
  - agenda.md
  - guidelines.md
  - committee.md
  - previous.md
